In [1]:
import pandas as pd
from sklearn.impute import SimpleImputer
import numpy as np

In [2]:
virus_= pd.read_csv('enteric_virus.csv')

In [3]:
virus = virus_.copy()

In [4]:
virus = virus.loc[:, "Age": ]

In [5]:
virus

,Age,DOB_Year,Year of enrollment,Date of hospital entry,AdminDate,SiteRecruitment,Gender,DateOnset,DateDischOrDeath,Length of stay,...,Parechovirus,Picobirnavirus,Porprismacovirus,Protoparvovirus,Rotavirus,Rubulavirus,Salivirus,Sapovirus,Unclassified virus,is_coinf
0,89,1923,2012,2012/10/31,2012/11/1,4,2,2012/10/31,2012/11/4,4,...,2,2,2,2,2,2,2,2,2,NaN
1,1,2011,2012,2012/11/1,2012/11/1,4,2,2012/10/29,2012/11/5,4,...,2,2,2,2,2,2,2,2,2,3.0
2,29,1983,2012,2012/11/2,2012/11/2,4,2,2012/11/1,2012/11/4,2,...,2,2,2,2,2,2,2,2,2,NaN
3,0,2012,2012,2012/11/9,2012/11/9,4,1,2012/11/8,2012/11/11,2,...,2,2,2,2,2,2,2,2,2,NaN
4,1,2011,2012,2012/11/15,2012/11/15,4,1,2012/11/15,2012/11/20,5,...,2,2,2,2,2,2,2,2,2,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
702,30,1983,2013,2013/11/30,2013/12/1,5,1,2013/11/21,2013/12/10,10,...,2,2,2,2,2,2,2,2,2,1.0
703,0,2013,2013,2013/12/17,2013/12/18,5,1,2013/12/3,2013/12/21,4,...,2,2,2,2,2,2,2,1,2,2.0
704,0,2013,2013,2013/12/25,2014/1/2,5,1,2013/12/16,2014/1/9,15,...,2,2,2,2,2,2,2,1,2,3.0
705,1,2013,2014,2014/4/6,2014/4/10,5,1,2014/3/7,2014/4/17,11,...,2,2,2,2,2,2,2,2,2,2.0
706,3,2011,2014,2014/4/8,2014/4/10,5,1,2014/4/8,2014/4/17,9,...,2,2,2,2,2,2,2,2,2,3.0

In [6]:
print(virus["BloodStool"].value_counts())
print(virus["MucoidStool"].value_counts())
print(virus["AbdominalPain"].value_counts())
print(virus["NumberDiarEpi"].value_counts())
print(virus["ThreeDaysFever"].value_counts())

print("Length of stay unique value counts:{}".format(len(virus["Length of stay"].unique())))
print(virus["Length of stay"].value_counts())

print("CentrallyCity unique value counts:{}".format(len(virus["CentrallyCity"].unique())))
print("ProvincialCity unique value counts:{}".format(len(virus["ProvincialCity"].unique())))
print(virus["CentrallyCity"].unique())
print(virus["ProvincialCity"].unique())
print("CentrallyCity value counts:{}".format(virus["CentrallyCity"].value_counts()))
print("ProvincialCity value counts:{}".format(virus["ProvincialCity"].value_counts()))

print("ContactDiar unique value counts:{}".format(len(virus["ContactDiar"].unique())))
print(virus["ContactDiar"].unique())
print(virus["ContactDiar"].value_counts())

print(virus["AbdominalPain"].value_counts())

print(virus["ThreeDaysFever"].value_counts())

print("NumberDiarEpi unique value counts:{}".format(len(virus["NumberDiarEpi"].unique())))
print(virus["NumberDiarEpi"].unique())
print(virus["NumberDiarEpi"].value_counts())
print(virus["NumberDiarEpi"].isna().sum())

print("HaemoglobinResult unique value counts:{}".format(len(virus["HaemoglobinResult"].unique())))
print(virus["HaemoglobinResult"].isna().sum())
print(virus["EosinophilsResult"].isna().sum())
print(virus["PlateletsResult"].isna().sum())

print("KnownTemp  unique value counts:{}".format(len(virus["KnownTemp"].unique())))
print(virus["KnownTemp"].unique())
print(virus["KnownTemp"].value_counts())
print(virus["KnownTemp"].isna().sum())


print("Temp unique value counts:{}".format(len(virus["Temp"].unique())))
print(virus["Temp"].isna().sum())

print(virus["Tap"].value_counts())
print(virus["Well"].value_counts())
print(virus["River"].value_counts())
print(virus["Pond"].value_counts())
print(virus["Bottled"].value_counts())
print(virus["OtherWS"].value_counts())

print(virus["KeepAnimal"].value_counts())
print(virus["KillingAnimal"].value_counts())
print(virus["EatCookRawMeat"].value_counts())
print(virus["Rotavirus.PCR."].value_counts())
print(virus["Norovirus2.PCR."].value_counts())
print(virus["Norovirus1.PCR."].value_counts())
print(virus["Aichivirus.PCR."].value_counts())
print(virus["Adenovirus.PCR."].value_counts())
print(virus["Sapovirus.PCR."].value_counts())
print(virus["Astrovirus.PCR."].value_counts())

viruses=['Rotavirus', 'Norovirus', 'Sapovirus', 'Kobuvirus','Mastadenovirus','Mamastrovirus','Alphapapillomavirus',
         'Alphapolyomavirus', 'Alphatorquevirus', 'Betapapillomavirus', 'Betapolyomavirus', 'Betatorquevirus', 'Bocaparvovirus',
         'Cardiovirus', 'Circovirus', 'Cosavirus', 'Cytomegalovirus', 'Enterovirus', 'Gammatorquevirus', 'Gemycircularvirus',
         'Gemykibivirus', 'Gemykrogvirus', 'Husavirus', 'Lymphocryptovirus', 'Morbillivirus', 'Parechovirus', 'Picobirnavirus',
         'Porprismacovirus', 'Protoparvovirus', 'Rubulavirus', 'Salivirus', 'Unclassified virus']
print(len(viruses))
for i in viruses:
    print(virus[i].value_counts())
    
    
print(virus["is_coinf"].value_counts())   
print(virus["is_coinf"].isna().sum())

2    679
1     25
9      3
Name: BloodStool, dtype: int64
2    597
1    106
9      4
Name: MucoidStool, dtype: int64
2    393
1    302
9     12
Name: AbdominalPain, dtype: int64
6.0     275
8.0     146
10.0     97
7.0      30
5.0      29
14.0     24
4.0      18
20.0     18
12.0     13
9.0       9
15.0      7
3.0       4
2.0       4
16.0      3
13.0      3
30.0      2
11.0      1
17.0      1
18.0      1
0.0       1
Name: NumberDiarEpi, dtype: int64
2    363
1    340
9      4
Name: ThreeDaysFever, dtype: int64
Length of stay unique value counts:18
2     147
3     139
4     133
5      97
6      64
1      37
7      31
8      21
9       9
0       6
10      5
15      5
11      4
14      4
12      2
19      1
13      1
33      1
Name: Length of stay, dtype: int64
CentrallyCity unique value counts:7
ProvincialCity unique value counts:26
['Dong Thap' 'Dak Lak' 'Dak Nong' 'Khanh Hoa' 'Thua Thien - Hue'
 'Quang Tri' 'Quang Binh']
['TP. Cao Lanh' 'Thanh Binh' 'Cao Lanh' 'Tam Nong' 'Lap Vo' 'Chau Thanh'
 'Thi Xa Hong Ngu' 'Thap Muoi' 'Lai Vung' 'Krong Nang' 'Buon Ma Thuot'
 'Buon Ho' "Cu M'gar" 'Krong No' 'Krong Ana' 'Dak Mil' 'Dak Song'
 'Krong Pak' 'Nha Trang' 'Ninh Hoa' 'Dien Khanh' 'Phong Dien'
 'Trieu Phong' 'Cam Lo' 'Dong Ha' 'Dong Hoi']
CentrallyCity value counts:Dong Thap           670
Dak Lak              20
Khanh Hoa             8
Quang Tri             3
Dak Nong              3
Thua Thien - Hue      2
Quang Binh            1
Name: CentrallyCity, dtype: int64
ProvincialCity value counts:TP. Cao Lanh       339
Cao Lanh           303
Buon Ma Thuot       12
Thanh Binh          10
Lap Vo              10
Nha Trang            5
Thap Muoi            3
Krong Ana            3
Cu M'gar             2
Phong Dien           2
Ninh Hoa             2
Chau Thanh           2
Cam Lo               1
Trieu Phong          1
Dak Mil              1
Dien Khanh           1
Dong Ha              1
Krong Pak            1
Thi Xa Hong Ngu      1
Buon Ho              1
Lai Vung             1
Dong Hoi             1
Krong Nang           1
Tam Nong             1
Dak Song             1
Krong No             1
Name: ProvincialCity, dtype: int64
ContactDiar unique value counts:3
[2 9 1]
2    675
1     18
9     14
Name: ContactDiar, dtype: int64
2    393
1    302
9     12
Name: AbdominalPain, dtype: int64
2    363
1    340
9      4
Name: ThreeDaysFever, dtype: int64
NumberDiarEpi unique value counts:21
[nan  5. 10. 20.  6.  3. 15.  8.  4.  7. 14. 16.  9. 17. 11. 18. 13. 12.
  2. 30.  0.]
6.0     275
8.0     146
10.0     97
7.0      30
5.0      29
14.0     24
4.0      18
20.0     18
12.0     13
9.0       9
15.0      7
3.0       4
2.0       4
16.0      3
13.0      3
30.0      2
11.0      1
17.0      1
18.0      1
0.0       1
Name: NumberDiarEpi, dtype: int64
21
HaemoglobinResult unique value counts:113
1
12
2
KnownTemp  unique value counts:3
[nan  1.  2.]
1.0    281
2.0     59
Name: KnownTemp, dtype: int64
367
Temp unique value counts:23
426
False    377
True     330
Name: Tap, dtype: int64
False    683
True      24
Name: Well, dtype: int64
False    535
True     172
Name: River, dtype: int64
False    704
True       3
Name: Pond, dtype: int64
False    527
True     180
Name: Bottled, dtype: int64
False    707
Name: OtherWS, dtype: int64
1    404
2    303
Name: KeepAnimal, dtype: int64
2    693
1     14
Name: KillingAnimal, dtype: int64
1    522
2    185
Name: EatCookRawMeat, dtype: int64
-      464
Pos    243
Name: Rotavirus.PCR., dtype: int64
-      645
Pos     62
Name: Norovirus2.PCR., dtype: int64
-    707
Name: Norovirus1.PCR., dtype: int64
-      704
Pos      3
Name: Aichivirus.PCR., dtype: int64
-      685
Pos     22
Name: Adenovirus.PCR., dtype: int64
-      696
Pos     11
Name: Sapovirus.PCR., dtype: int64
-      703
Pos      4
Name: Astrovirus.PCR., dtype: int64
32
2    556
1    151
Name: Rotavirus, dtype: int64
2    618
1     89
Name: Norovirus, dtype: int64
2    650
1     57
Name: Sapovirus, dtype: int64
2    702
1      5
Name: Kobuvirus, dtype: int64
2    656
1     51
Name: Mastadenovirus, dtype: int64
2    685
1     22
Name: Mamastrovirus, dtype: int64
2    706
1      1
Name: Alphapapillomavirus, dtype: int64
2    707
Name: Alphapolyomavirus, dtype: int64
2    635
1     72
Name: Alphatorquevirus, dtype: int64
2    707
Name: Betapapillomavirus, dtype: int64
2    702
1      5
Name: Betapolyomavirus, dtype: int64
2    654
1     53
Name: Betatorquevirus, dtype: int64
2    698
1      9
Name: Bocaparvovirus, dtype: int64
2    703
1      4
Name: Cardiovirus, dtype: int64
2    707
Name: Circovirus, dtype: int64
2    702
1      5
Name: Cosavirus, dtype: int64
2    704
1      3
Name: Cytomegalovirus, dtype: int64
2    655
1     52
Name: Enterovirus, dtype: int64
2    688
1     19
Name: Gammatorquevirus, dtype: int64
2    706
1      1
Name: Gemycircularvirus, dtype: int64
2    705
1      2
Name: Gemykibivirus, dtype: int64
2    705
1      2
Name: Gemykrogvirus, dtype: int64
2    706
1      1
Name: Husavirus, dtype: int64
2    707
Name: Lymphocryptovirus, dtype: int64
2    705
1      2
Name: Morbillivirus, dtype: int64
2    673
1     34
Name: Parechovirus, dtype: int64
2    670
1     37
Name: Picobirnavirus, dtype: int64
2    706
1      1
Name: Porprismacovirus, dtype: int64
2    706
1      1
Name: Protoparvovirus, dtype: int64
2    705
1      2
Name: Rubulavirus, dtype: int64
2    697
1     10
Name: Salivirus, dtype: int64
2    681
1     26
Name: Unclassified virus, dtype: int64
1.0    250
2.0    124
3.0     50
4.0     11
5.0      5
Name: is_coinf, dtype: int64
267

In [7]:
common_viruses=['Rotavirus', 'Norovirus', 'Sapovirus', 'Kobuvirus','Mastadenovirus','Mamastrovirus']

uncommon_viruses=['Alphapapillomavirus',
         'Alphapolyomavirus', 'Alphatorquevirus', 'Betapapillomavirus', 'Betapolyomavirus', 'Betatorquevirus', 'Bocaparvovirus',
         'Cardiovirus', 'Circovirus', 'Cosavirus', 'Cytomegalovirus', 'Enterovirus', 'Gammatorquevirus', 'Gemycircularvirus',
         'Gemykibivirus', 'Gemykrogvirus', 'Husavirus', 'Lymphocryptovirus', 'Morbillivirus', 'Parechovirus', 'Picobirnavirus',
         'Porprismacovirus', 'Protoparvovirus', 'Rubulavirus', 'Salivirus', 'Unclassified virus']

In [8]:
for i in range(len(common_viruses)-1):
    for j in range(i+1,len(common_viruses)):
        f = common_viruses[i]
        l = common_viruses[j]
        virus[f+'_'+l]=virus[f]+virus[l]
        virus[f+'_'+l].replace([2,3,4],[1,0,0], inplace=True)

In [9]:
virus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 707 entries, 0 to 706
Columns: 101 entries, Age to Mastadenovirus_Mamastrovirus
dtypes: bool(7), float64(19), int64(62), object(13)
memory usage: 524.2+ KB

In [10]:
virus = virus.loc[:, (virus != 0).any(axis=0)]

In [11]:
virus = virus[virus["BloodStool"]!=9]

In [12]:
virus = virus[virus["MucoidStool"]!=9]

In [13]:
virus = virus[virus["AbdominalPain"]!=9]

In [14]:
virus = virus[virus["ThreeDaysFever"]!=9]

In [15]:
# date object type change
virus["Date of hospital entry"] = pd.to_datetime(virus["Date of hospital entry"])
virus["AdminDate"] = pd.to_datetime(virus["AdminDate"])
virus["DateOnset"] = pd.to_datetime(virus["DateOnset"])
virus["DateDischOrDeath"] = pd.to_datetime(virus["DateDischOrDeath"])

In [16]:
virus.BloodStool.replace(2, 0, inplace=True)
virus.MucoidStool.replace(2,0, inplace=True)
virus.ThreeDaysFever.replace(2,0, inplace=True)
virus.AbdominalPain.replace(2,0, inplace=True)

In [17]:
imp=SimpleImputer(missing_values=np.nan, strategy='median' )
imp.fit(virus[['NumberDiarEpi']])
virus[['NumberDiarEpi']]=imp.transform(virus[['NumberDiarEpi']])

In [18]:
#virus.AbdominalPain.replace([1,2],['Yes', 'No'], inplace=True)
#virus.ThreeDaysFever.replace([1,2],['Yes', 'No'], inplace=True)

In [19]:
imp=SimpleImputer(missing_values=np.nan, strategy='median' )
imp.fit(virus[['HaemoglobinResult']])
virus[['HaemoglobinResult']]=imp.transform(virus[['HaemoglobinResult']])

imp.fit(virus[['WhiteCellsResult']])
virus[['WhiteCellsResult']]=imp.transform(virus[['WhiteCellsResult']])

imp.fit(virus[['NeutrophilsResult']])
virus[['NeutrophilsResult']]=imp.transform(virus[['NeutrophilsResult']])

imp.fit(virus[['LymphocytesResult']])
virus[['LymphocytesResult']]=imp.transform(virus[['LymphocytesResult']])

imp.fit(virus[['EosinophilsResult']])
virus[['EosinophilsResult']]=imp.transform(virus[['EosinophilsResult']])

imp.fit(virus[['PlateletsResult']])
virus[['PlateletsResult']]=imp.transform(virus[['PlateletsResult']])

In [20]:
#virus["KnownTemp"] = virus["KnownTemp"].fillna(9)
#virus["KnownTemp"].replace([1,2,9],['Yes', 'No','NA'], inplace=True)

In [21]:
virus.loc[ (virus.Temp.notnull()), 'Temp' ] = 1
virus.loc[ (virus.Temp.isnull()), 'Temp' ] = 0

In [22]:
for i in viruses:
    virus[i].replace([1,2],['Yes', 'No'], inplace=True)

In [23]:

#virus["is_coinf"] = virus["is_coinf"].fillna(0)
virus.dropna(subset = ["is_coinf"], inplace=True)
virus["is_coinf"] = virus["is_coinf"].mask(virus["is_coinf"] ==1, 0) 
virus["is_coinf"] = virus["is_coinf"].mask(virus["is_coinf"] >1, 1) 
#virus["is_coinf"].replace([1,2],['NO', 'YES'], inplace=True)
#dummies_is_coinf = pd.get_dummies(virus['is_coinf'], prefix= 'is_coinf')

#virus = pd.concat([virus, dummies_is_coinf], axis=1)
#virus.drop(['is_coinf'], axis=1, inplace=True)
virus

,Age,DOB_Year,Year of enrollment,Date of hospital entry,AdminDate,SiteRecruitment,Gender,DateOnset,DateDischOrDeath,Length of stay,...,Rotavirus_Norovirus,Rotavirus_Sapovirus,Rotavirus_Kobuvirus,Rotavirus_Mastadenovirus,Rotavirus_Mamastrovirus,Norovirus_Sapovirus,Norovirus_Mastadenovirus,Norovirus_Mamastrovirus,Sapovirus_Mastadenovirus,Sapovirus_Mamastrovirus
4,1,2011,2012,2012-11-15,2012-11-15,4,1,2012-11-15,2012-11-20,5,...,0,0,0,0,0,0,0,0,0,0
6,27,1985,2012,2012-11-13,2012-11-15,4,2,2012-11-14,2012-11-17,4,...,0,0,0,0,0,1,0,0,0,0
7,80,1932,2012,2012-11-15,2012-11-15,4,2,2012-11-12,2012-11-23,8,...,0,0,0,0,0,0,0,0,0,0
9,0,2012,2012,2012-11-26,2012-11-26,4,2,2012-11-23,2012-11-29,3,...,0,0,0,0,0,0,0,0,0,0
11,0,2012,2012,2012-12-04,2012-12-04,4,1,2012-11-30,2012-12-06,2,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
702,30,1983,2013,2013-11-30,2013-12-01,5,1,2013-11-21,2013-12-10,10,...,0,0,0,0,0,0,0,0,0,0
703,0,2013,2013,2013-12-17,2013-12-18,5,1,2013-12-03,2013-12-21,4,...,0,0,0,0,0,1,0,0,0,0
704,0,2013,2013,2013-12-25,2014-01-02,5,1,2013-12-16,2014-01-09,15,...,0,0,0,0,0,1,0,0,0,0
705,1,2013,2014,2014-04-06,2014-04-10,5,1,2014-03-07,2014-04-17,11,...,0,0,0,0,0,0,0,0,0,0
706,3,2011,2014,2014-04-08,2014-04-10,5,1,2014-04-08,2014-04-17,9,...,0,0,0,0,0,0,0,0,0,0

In [24]:
virus.to_csv('virus_modified6.csv')

In [58]:
virus.head()

,Age,DOB_Year,Year of enrollment,Date of hospital entry,AdminDate,SiteRecruitment,Gender,DateOnset,DateDischOrDeath,Length of stay,...,Rotavirus_Norovirus,Rotavirus_Sapovirus,Rotavirus_Kobuvirus,Rotavirus_Mastadenovirus,Rotavirus_Mamastrovirus,Norovirus_Sapovirus,Norovirus_Mastadenovirus,Norovirus_Mamastrovirus,Sapovirus_Mastadenovirus,Sapovirus_Mamastrovirus
0,89,1923,2012,2012-10-31,2012-11-01,4,2,2012-10-31,2012-11-04,4,...,0,0,0,0,0,0,0,0,0,0
2,29,1983,2012,2012-11-02,2012-11-02,4,2,2012-11-01,2012-11-04,2,...,0,0,0,0,0,0,0,0,0,0
4,1,2011,2012,2012-11-15,2012-11-15,4,1,2012-11-15,2012-11-20,5,...,0,0,0,0,0,0,0,0,0,0
6,27,1985,2012,2012-11-13,2012-11-15,4,2,2012-11-14,2012-11-17,4,...,0,0,0,0,0,1,0,0,0,0
7,80,1932,2012,2012-11-15,2012-11-15,4,2,2012-11-12,2012-11-23,8,...,0,0,0,0,0,0,0,0,0,0